v1.0.0: Now supporting multiple backends!
Signed-off-by: Kwpolska <kwpolska@gmail.com>

diff --git a/release b/release
--- a/release
+++ b/release
@@ -9,16 +9,19 @@ if [[ $version = '' ]]; then
     read version
 fi
 
+rm -rf trashman.egg-info __pycache__ trashman/__pycache__ trashman/backends/__pycache__ dist build
+
 date=$(date '+%Y-%m-%d')
 datel=$(date '+%Y-%m-%d %H:%M%z')
 
-sed "s/version=.*/version='$version',/" setup.py -i
+sed "s/version=.*/version='$version',/g" setup.py -i
 sed "s/version = .*/version = '$version'/g" docs/conf.py -i
 sed "s/release = .*/release = '$version'/g" docs/conf.py -i
 sed "s/:Version: .*/:Version: $version/g" docs/*.rst -i
 sed "s/BUILDer .* do/BUILDer $version do/g" docs/index.rst -i
-sed "s/# Trashman v.*/# Trashman v$version/g" trashman.py -i
-sed "s/__version__ = .*/__version__ = '$version'/" trashman.py -i
+sed "s/# Trashman v.*/# Trashman v$version/g" trashman/*.py -i
+sed "s/# Trashman v.*/# Trashman v$version/g" trashman/backends/*.py -i
+sed "s/__version__ = .*/__version__ = '$version'/" trashman/__init__.py -i
 sed "s/pkgver=.*/pkgver=$version/" PKGBUILD -i
 
 sed "s/:Date: .*/:Date: $date/g" docs/*.rst -i
@@ -30,7 +33,7 @@ rm docs/trashman.8.gz | true
 rst2man docs/trashman.rst > docs/trashman.8
 gzip docs/trashman.8
 
-xgettext -c trashman.py -o ./messages.pot
+xgettext -c ./trashman/*.py ./trashman/backends/*.py -o ./messages.pot
 
 sed '1,+17d' ./messages.pot > ./messages.pot.tmp
 
@@ -79,7 +82,11 @@ if [[ $? = 1 ]]; then
     exit 1
 fi
 
-rm -rf trashman.egg-info __pycache__ trashman/__pycache__ trashman.pyc
+./tests.py
+if [[ $? = 1 ]]; then
+    echo "Tests failed.  Fix your code or don't come back."
+    exit 1
+fi
 ./setup.py sdist upload
 
 md5out=$(md5sum 'dist/'$project'-'$version'.tar.gz'|awk '{print $1}')
@@ -93,14 +100,31 @@ burp -u Kwpolska -c system trashman.src.tar.gz
 cd ..
 rm -rf MKPKGBUILD
 
-echo 'Commit message (sans the version?)'
-echo -n '> '
-read commitmsg
+if [[ $2 != '-c' ]]; then
+    echo 'Commit message (sans the version?)'
+    echo -n '> '
+    read commitmsg
+    if [[ commitmsg = '' ]]; then
+        cm='t'
+    fi
+else
+    cm='t'
+fi
 
-rm -rf trashman.egg-info __pycache__ trashman/__pycache__ trashman.pyc
+rm -rf trashman.egg-info __pycache__ trashman/__pycache__ trashman/backends/__pycache__ dist build
 
 git add *
-if [[ $2 = '-c' ]]; then
+if [[ $? != '1' ]]; then
+    echo 'Open another terminal and fix the errors.'
+    read dn
+    git add *
+    if [[ $? != '1' ]]; then
+        echo 'But please test your changes using that other terminal.'
+        read dn2
+        git add *
+fi
+
+if [[ $cm = 't' ]]; then
     git commit -as
 else
     git commit -asm "v$version: $commitmsg"
